"""Add city and area to user and vendor tables

Revision ID: 5237beeee953
Revises: 857286d0ee6e
Create Date: 2024-12-03 01:39:01.234276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5237beeee953'
down_revision = '857286d0ee6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('area')
        batch_op.drop_column('city')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('area')
        batch_op.drop_column('city')

    # ### end Alembic commands ###
