"""Added payment_method and payment_status to Order model

Revision ID: 7bd0c6642f6e
Revises: 4f1607bea653
Create Date: 2025-04-11 19:28:45.994046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bd0c6642f6e'
down_revision = '4f1607bea653'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('payment_status')
        batch_op.drop_column('payment_method')

    # ### end Alembic commands ###
